name: Update README

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity

    steps:
      - uses: actions/checkout@v2
      - uses: DenverCoderOne/github-activity-readme@commit-username-and-email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_USERNAME: "tjgurwara99"
          COMMIT_EMAIL: "tjgurwara99@gmail.com"  
